import re
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY


def clean_markdown(text: str) -> str:
    """Strip markdown symbols for plain PDF rendering."""
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'#{1,6}\s*', '', text)
    text = re.sub(r'`(.*?)`', r'\1', text)
    text = re.sub(r'\[(.*?)\]\(.*?\)', r'\1', text)
    return text.strip()


def export_to_pdf(topic: str, report_content: str, output_path: str = "research_report.pdf") -> str:
    """Export the final research report to a styled PDF."""

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=20 * mm,
    )

    # --- Styles ---
    base_styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        fontSize=24,
        leading=30,
        textColor=colors.HexColor("#0f172a"),
        fontName="Helvetica-Bold",
        spaceAfter=4,
        alignment=TA_LEFT,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        fontSize=11,
        textColor=colors.HexColor("#64748b"),
        fontName="Helvetica",
        spaceAfter=2,
        alignment=TA_LEFT,
    )

    section_heading_style = ParagraphStyle(
        "SectionHeading",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#1e40af"),
        fontName="Helvetica-Bold",
        spaceBefore=14,
        spaceAfter=6,
    )

    body_style = ParagraphStyle(
        "Body",
        fontSize=10,
        leading=16,
        textColor=colors.HexColor("#1e293b"),
        fontName="Helvetica",
        spaceAfter=8,
        alignment=TA_JUSTIFY,
    )

    bullet_style = ParagraphStyle(
        "Bullet",
        fontSize=10,
        leading=15,
        textColor=colors.HexColor("#334155"),
        fontName="Helvetica",
        leftIndent=14,
        spaceAfter=4,
        bulletIndent=4,
    )

    # --- Build story ---
    story = []
    timestamp = datetime.now().strftime("%B %d, %Y • %I:%M %p")

    # Header block
    story.append(Paragraph("AI Research Assistant", subtitle_style))
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(topic, title_style))
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(f"Generated on {timestamp}", subtitle_style))
    story.append(Spacer(1, 4 * mm))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1e40af"), spaceAfter=10))

    # Parse and render content
    lines = report_content.split("\n")

    for line in lines:
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 3 * mm))
            continue

        # Section headings (markdown ##)
        if stripped.startswith("## "):
            text = clean_markdown(stripped[3:])
            story.append(Paragraph(text, section_heading_style))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=4))

        elif stripped.startswith("# "):
            text = clean_markdown(stripped[2:])
            story.append(Paragraph(text, section_heading_style))

        # Bullet points
        elif stripped.startswith("- ") or stripped.startswith("* "):
            text = clean_markdown(stripped[2:])
            story.append(Paragraph(f"• {text}", bullet_style))

        # Numbered list
        elif re.match(r'^\d+\.', stripped):
            text = clean_markdown(stripped)
            story.append(Paragraph(text, bullet_style))

        # Normal paragraph
        else:
            text = clean_markdown(stripped)
            if text:
                story.append(Paragraph(text, body_style))

    # Footer line
    story.append(Spacer(1, 8 * mm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=6))
    story.append(Paragraph("Generated by AI Research Assistant • Powered by Google Gemini + CrewAI", subtitle_style))

    doc.build(story)
    return output_path
